version: "3.8"
services:
  # local_db:
  #   image: postgres
  #   volumes:
  #     - ./sql:/docker-entrypoint-initdb.d
  #     - ./data/db:/var/lib/postgresql/data
  #   ports:
  #     - 5431:5432
  #   env_file: .env
  #   container_name: local_db

  shopsurfer_api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    image: shopsurfer_api:latest
    container_name: shopsurfer_api
    command: "gunicorn shop_surfer_python.wsgi:application -b 0.0.0.0:8000"
    # depends_on:
    #   - local_db
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    container_name: shopsurfer_nginx
    depends_on:
      - shopsurfer_api
    restart: always
