# Generated by Django 4.2.2 on 2023-06-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(default='regular', max_length=100),
        ),
    ]
