# Generated by Django 4.2.2 on 2023-06-28 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shippingaddress_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 6, 28, 12, 14, 22, 752367)),
            preserve_default=False,
        ),
    ]
