# Generated by Django 4.2.2 on 2023-07-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_cart_cart_items_alter_order_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', through='shop.ProductCategory', to='shop.category'),
        ),
    ]
