# Generated by Django 4.2.2 on 2023-07-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
